### ISSUE TITLE
Python 3.5 incompatibility

### ISSUE THREAD

**Issue by andrei-a-papou** [AlexisBRENON/ewmh_m2m#1]
Hello, and thank you for this utility. I'd love to try it out, but am currently unable to install.

Running Debian Stretch here.

I can't install locally, only in a virtual environment. Setting it up as usual:
```
cd ~/bin
python3 -m venv ewmh_m2m 
. ewmh_m2m/bin/activate
pip install ewmh-m2m
```

The result is:
```
Collecting ewmh-m2m
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement ewmh-m2m (from versions: )
No matching distribution found for ewmh-m2m

```

I tried upgrading `pip` inside the virtualenv and try again, but it also failed:

```
python -m pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.3.1


pip install ewmh-m2m               
ERROR: Could not find a version that satisfies the requirement ewmh-m2m (from versions: none)
ERROR: No matching distribution found for ewmh-m2m
```

I would appreciate any pointers on how to proceed at this point. Either fixing the virtualenv installation, or maybe running it from a local cloned repo?

Thank you.

**Comment by AlexisBRENON** [comment]
From what I can see from here, the most obvious reason for this error is that your Python version does not match the Python specifier from the package (`Python >= 3.7`).
Actually, I did not test my script with other versions. I am going to release a new version, less restrictive about Python version. Let me know if you have any other problem. Thanks for the feedback.

**Comment by AlexisBRENON** [comment]
Can you please give me your Python version?

**Comment by AlexisBRENON** [comment]
I just tried with Python 3.5. Unfortunately I used some features that are not available before Python 3.7 (for example the `auto` from the `enum` package).

If you want to make it Python 3.5 compatible, PRs are welcome :wink:
To run from a local repo:
- clone the repo
- create your virtual environment and activate it
- install local copy of the script: `pip install .`
- enjoy.

**Comment by andrei-a-papou** [comment]
@AlexisBRENON  thanks for a prompt response!

My python version is:
```
python3 -V
Python 3.5.3
```

So you are probably right, it's a version issue. Unfortunately, I know very little python3 to submit a PR :)

I'll keep an eye on this repo, though, and wait for an update, whenever it comes. Thanks again!

**Comment by AlexisBRENON** [comment]
I just made a new release which is Python3.5 compatible (from what I tested).
You should be able to install it now. Let me know if you encounter other issues.

By the way, you should probably not use a virtualenv to install it, or you will be not able to use it easily (you will have to activate your virtual environment before calling the entrypoint).

**Comment by andrei-a-papou** [comment]
Alexis, thank you. It installs now and seems to run great. 

Windows are moved smoothly and seamlessly, much nicer and with no flicker compared to the homegrown `xdotool`- and `wmctrl`-based script that I currently use.

I will start using it more and report any errors or suggestions.

Thanks a lot again!
