### ISSUE TITLE
No sibling screen found - Error

### ISSUE THREAD

**Issue by tobip** [AlexisBRENON/ewmh_m2m#14]
Thanks for the great script! Unfortunately this is what I get:

    $ move-to-monitor -v -v
    DEBUG:ewmh_m2m.__main__:Detected screens: {Geometry(2960, 0, 1920, 1200), Geometry(0, 176, 1280, 1024), Geometry(1280, 150, 1680, 1050)}
    DEBUG:ewmh_m2m.__main__:Containing screen: Geometry(0, 176, 1280, 1024)
    CRITICAL:ewmh_m2m.__main__:No sibling screen found

This is my screen configuration:
![image](https://user-images.githubusercontent.com/3918330/72931928-08614000-3d5f-11ea-9e82-6182ba5e399d.png)

Any suggestions?

**Comment by AlexisBRENON** [comment]
Thanks for the report.

Yes, I have a suggestion. Align the top of your screens :laughing: 
As a lazy developer, I discover the left/right screens by looking for the ones with [the same `y` value](https://github.com/AlexisBRENON/ewmh_m2m/blob/master/src/ewmh_m2m/screen.py#L20) (the vertical coordinate of the top edge of the screen) than the current one. While coding this, I said to myself "You're lazy, this is bad, and it will not work for anyone not aligning the top of their screens."

So, long say short, let me some days to find time to fix this!

**Comment by tobip** [comment]
Alright :-)
No worries, I am using another script at the moment that works fine for me for now.
Thanks a lot!

**Comment by AlexisBRENON** [comment]
I just made a PR (#15).
Are you able to test it (before I merge and release it)?

**Comment by tobip** [comment]
How can I do this?

**Comment by AlexisBRENON** [comment]
Fixed in version [v1.1.3](https://pypi.org/project/ewmh-m2m/1.1.3/)
