### ISSUE TITLE
Window switching doesnt work for fullscreened windows (not maximized, but fullscreened via F11)

### ISSUE THREAD

**Issue by balisongjam** [AlexisBRENON/ewmh_m2m#17]

**Comment by AlexisBRENON** [comment]
Hi,

Thanks for the report. Due to the COVID, I am home-office and do not have dual screen anymore, so I cannot try to reproduce nor debug the behavior.

Can you run `move-to-monitor` with debug output and report the output : `move-to-monitor -vvv`

Kinds.
