### ISSUE TITLE
binding command to a keyboard shortcut

### ISSUE THREAD

**Issue by negishubham** [AlexisBRENON/ewmh_m2m#21]
Hi, 

After the pip installation how to bind the move-to-monitor command to a keyboard shortcut? 

Thanks

**Comment by AlexisBRENON** [comment]
Hi. This depends of your distro and/or desktop environment. 
Here is an example for Xfce: https://unix.stackexchange.com/questions/44643/change-global-keyboard-shortcuts

**Comment by negishubham** [comment]
Alexis, 

I know how to add a command to the shortcut. But I am not sure how to bring move-to-monitor command (that I installed using this repo) in the image below. 

One way I read about doing this was to add the command to a script and add it as I have done in the image. But it doesn't seem to work. 

![Screenshot_2023-01-26_12-19-00](https://user-images.githubusercontent.com/30775753/214904962-56953d4d-4a87-436f-92c5-f54263d1a144.png)

Thanks

**Comment by AlexisBRENON** [comment]
You don’t need to use a intermediate script. You probably have to specify the full absolute path to the `move-to-monitor` script.
You say that you installed it with the repo, how did you do ? `pip install ewmh-m2m` ?
I don’t know exactly where it is installed by default. Either something like `/usr/local/bin` or similar.

**Comment by AlexisBRENON** [comment]
In the code, you will find nothing more than the [entrypoint definition](https://github.com/AlexisBRENON/ewmh_m2m/blob/master/setup.cfg#L69).
Installation location is more related to your own Python/pip installation.

1. Can you run `move-to-monitor` from your terminal ?
2. If yes, what’s the output of `which move-to-monitor` ?
3. Take a look at the output of `pip show ewmh-m2m -v`, there should be a `Location` field, giving you some hints on where to find the `move-to-monitor` script.
4. Finally, what’s the output of `which pip` ?

**Comment by negishubham** [comment]
which move-to-monitor gives path as:  home/min/a/username/anaconda3/bin/move-to-monitor

But in the bin folder I can't find the script

**Comment by negishubham** [comment]
I found it. Thanks for the help Alexis
